### ISSUE TITLE
Video and audio broken 

### ISSUE THREAD

**Issue by srilanka195** [saramibreak/PVDTools#1]
I use PVDTools v1.4 and convert a Videonow (black and white) dump with this tool. I can use Irfanview v4.54 to view the frames and they are fine. The video i create plays audio and video fine on this dump as well.
I use PVDTools v1.4 on a Videonow color or xp dump and frames have vertical lines and sound is broken in some areas of my created video. The video does play audio and video in some areas though, just fine. So, audio goes in and out on xp and color dumps, but black and white dumps are fine throughout the whole video.  Any suggestions?

**Comment by saramibreak** [comment]
> Videonow color or xp dump and frames have vertical lines and sound is broken in some areas of my created video.

Tell me the disc title, please.

**Comment by srilanka195** [comment]
Scooby doo (VideoNow color), Batman (VideoNow Xp) are having vertical lines in the .ppm frames. I have tried a few others with same results (.ppm files). VideoNow (.pgm files) are correct and Vdub makes the video with audio and video correctly. Thanks for any kind of help.

**Comment by saramibreak** [comment]
[PVDTools.zip](https://github.com/saramibreak/PVDTools/files/5179026/PVDTools.zip)
- fixed: seek position if pregap exists in the track.

**Comment by srilanka195** [comment]
Thank you. Will test this w/ fix.

**Comment by srilanka195** [comment]
I tested with the fixed  version of PVDTools, but i am still getting broken audio and video. I have included clip in .zip
[Scooby doo.zip](https://github.com/saramibreak/PVDTools/files/5184989/Scooby.doo.zip)

**Comment by saramibreak** [comment]
I ordered it. Estimated delivery:  Thu, Sep 24–Thu, Oct 1. Please wait...

**Comment by srilanka195** [comment]
That will work. Yeah, i did a few  Videonow discs (black, white) to .ppg files and irfanview, vdub created ,mp4's  correctly. Some reason, i try a color or xp disc to .ppm files (frames), and created video is not correct. I use all settings in  irfanview and vdub according the readme file provided. You can see with the .ppm files, mine have lines  and broken audio (viewing thru irfanview). Thanks for looking at this disc. I will check back here.

**Comment by saramibreak** [comment]
I got the disc and tested but all 12 tracks are no problem.
This tool only supports the split bin file (... (Track xx).bin) created by DiscImageCreator.
Img file does not support now.

**Comment by srilanka195** [comment]
Ok, thank you for testing. I have tried using DiscImageCreator (gui and command line), but i still cannot get DiscImageCreator to rip a videonow disc. My dvd drive is not fully compatible, i guess?  I ripped a videonow (black and white disc) and a videonow (color disc) to a single bin and cue file. These 2 discs were made to mp4 files correctly with PVDTools v1.4. I used a single bin, cue file from Scooby doo (videonow xp disc), but that is the problem disc. What is split bin file? Is that Track 01.bin, Track 02.bin, Track 03.bin? I ripped my videonow discs with Imgburn and 2 of my discs work with PVDTools v1.4.

**Comment by saramibreak** [comment]
[PVDTools_test.zip](https://github.com/saramibreak/PVDTools/files/5297603/PVDTools_test.zip)
support: normal dumping tool (imgburn etc.)

>Usage
         PVDTools.exe bw [cue file]
                 Output pgm (40 x 80 gray scale) and wav file
         PVDTools.exe color [cue file]
                 Output ppm (144 x 80 full color) and wav file
         PVDTools.exe xp [cue file]
                 Output ppm (144 x 80 full color) and wav file

**Comment by srilanka195** [comment]
Thank you saramibreak for this version , I will test this out. Thanks for all your help.

**Comment by srilanka195** [comment]
Tested an original Videonow color and xp disc. I used Imgburn to make single bin/cue files for each disc. This version of PVDTools + Vdub successfully created 2 .mp4 files w/ audio and video in sync. Worked perfect, thank you!

**Comment by saramibreak** [comment]
Thanks, testing. I released it as v1.5
